name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set node LTS
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm

      - name: Clean install dependencies
        run: npm ci

      - name: Test
        run: |
          npm run test -- --coverage --no-color 2>&1 | tee $GITHUB_STEP_SUMMARY
          exit_code=${PIPESTATUS[0]}
          exit $exit_code
